components:
  schemas:
    ConnectedOuterService:
      properties:
        name:
          type: string
        version:
          type: string
      title: ConnectedOuterService
      type: object
    InvalidTagWithReason:
      properties:
        name:
          type: string
        reason:
          type: string
      title: InvalidTagWithReason
      type: object
    InvalidTagsWithReason:
      properties:
        invalidLegalTags:
          items:
            $ref: '#/components/schemas/InvalidTagWithReason'
          type: array
      title: InvalidTagsWithReason
      type: object
    LegalTagDto:
      properties:
        description:
          type: string
        name:
          type: string
        properties:
          $ref: '#/components/schemas/Properties'
      title: LegalTagDto
      type: object
    LegalTagDtos:
      properties:
        legalTags:
          items:
            $ref: '#/components/schemas/LegalTagDto'
          type: array
      title: LegalTagDtos
      type: object
    Properties:
      properties:
        contractId:
          type: string
        countryOfOrigin:
          items:
            type: string
          type: array
        dataType:
          type: string
        expirationDate:
          example: yyyy-MM-dd
          type: string
        exportClassification:
          type: string
        originator:
          type: string
        personalData:
          type: string
        securityClassification:
          type: string
      title: Properties
      type: object
    ReadablePropertyValues:
      properties:
        countriesOfOrigin:
          additionalProperties:
            type: string
          type: object
        dataTypes:
          items:
            type: string
          type: array
          uniqueItems: true
        exportClassificationControlNumbers:
          items:
            type: string
          type: array
          uniqueItems: true
        otherRelevantDataCountries:
          additionalProperties:
            type: string
          type: object
        personalDataTypes:
          items:
            type: string
          type: array
          uniqueItems: true
        securityClassifications:
          items:
            type: string
          type: array
          uniqueItems: true
      title: ReadablePropertyValues
      type: object
    RequestLegalTags:
      properties:
        names:
          items:
            type: string
          type: array
      required:
      - names
      title: RequestLegalTags
      type: object
    ResponseEntity:
      properties:
        body:
          type: object
        statusCode:
          enum:
          - ACCEPTED
          - ALREADY_REPORTED
          - BAD_GATEWAY
          - BAD_REQUEST
          - BANDWIDTH_LIMIT_EXCEEDED
          - CHECKPOINT
          - CONFLICT
          - CONTINUE
          - CREATED
          - DESTINATION_LOCKED
          - EXPECTATION_FAILED
          - FAILED_DEPENDENCY
          - FORBIDDEN
          - FOUND
          - GATEWAY_TIMEOUT
          - GONE
          - HTTP_VERSION_NOT_SUPPORTED
          - IM_USED
          - INSUFFICIENT_SPACE_ON_RESOURCE
          - INSUFFICIENT_STORAGE
          - INTERNAL_SERVER_ERROR
          - I_AM_A_TEAPOT
          - LENGTH_REQUIRED
          - LOCKED
          - LOOP_DETECTED
          - METHOD_FAILURE
          - METHOD_NOT_ALLOWED
          - MOVED_PERMANENTLY
          - MOVED_TEMPORARILY
          - MULTIPLE_CHOICES
          - MULTI_STATUS
          - NETWORK_AUTHENTICATION_REQUIRED
          - NON_AUTHORITATIVE_INFORMATION
          - NOT_ACCEPTABLE
          - NOT_EXTENDED
          - NOT_FOUND
          - NOT_IMPLEMENTED
          - NOT_MODIFIED
          - NO_CONTENT
          - OK
          - PARTIAL_CONTENT
          - PAYLOAD_TOO_LARGE
          - PAYMENT_REQUIRED
          - PERMANENT_REDIRECT
          - PRECONDITION_FAILED
          - PRECONDITION_REQUIRED
          - PROCESSING
          - PROXY_AUTHENTICATION_REQUIRED
          - REQUESTED_RANGE_NOT_SATISFIABLE
          - REQUEST_ENTITY_TOO_LARGE
          - REQUEST_HEADER_FIELDS_TOO_LARGE
          - REQUEST_TIMEOUT
          - REQUEST_URI_TOO_LONG
          - RESET_CONTENT
          - SEE_OTHER
          - SERVICE_UNAVAILABLE
          - SWITCHING_PROTOCOLS
          - TEMPORARY_REDIRECT
          - TOO_EARLY
          - TOO_MANY_REQUESTS
          - UNAUTHORIZED
          - UNAVAILABLE_FOR_LEGAL_REASONS
          - UNPROCESSABLE_ENTITY
          - UNSUPPORTED_MEDIA_TYPE
          - UPGRADE_REQUIRED
          - URI_TOO_LONG
          - USE_PROXY
          - VARIANT_ALSO_NEGOTIATES
          type: string
        statusCodeValue:
          format: int32
          type: integer
      title: ResponseEntity
      type: object
    UpdateLegalTag:
      properties:
        contractId:
          type: string
        description:
          type: string
        expirationDate:
          format: date
          type: string
        name:
          type: string
      title: UpdateLegalTag
      type: object
    VersionInfo:
      properties:
        artifactId:
          type: string
        branch:
          type: string
        buildTime:
          type: string
        commitId:
          type: string
        commitMessage:
          type: string
        connectedOuterServices:
          items:
            $ref: '#/components/schemas/ConnectedOuterService'
          type: array
        groupId:
          type: string
        version:
          type: string
      title: VersionInfo
      type: object
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
info:
  contact: {}
  description: Api Documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  termsOfService: urn:tos
  title: Api Documentation
  version: '1.0'
openapi: 3.0.3
paths:
  /api/legal/v1/_ah/liveness_check:
    get:
      operationId: livenessCheckUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: livenessCheck
      tags:
      - health-check-api
  /api/legal/v1/_ah/readiness_check:
    get:
      operationId: readinessCheckUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: readinessCheck
      tags:
      - health-check-api
  /api/legal/v1/info:
    get:
      operationId: infoUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: info
      tags:
      - info-api
  /api/legal/v1/jobs/updateLegalTagStatus:
    get:
      operationId: checkLegalTagStatusChangesUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                enum:
                - ACCEPTED
                - ALREADY_REPORTED
                - BAD_GATEWAY
                - BAD_REQUEST
                - BANDWIDTH_LIMIT_EXCEEDED
                - CHECKPOINT
                - CONFLICT
                - CONTINUE
                - CREATED
                - DESTINATION_LOCKED
                - EXPECTATION_FAILED
                - FAILED_DEPENDENCY
                - FORBIDDEN
                - FOUND
                - GATEWAY_TIMEOUT
                - GONE
                - HTTP_VERSION_NOT_SUPPORTED
                - IM_USED
                - INSUFFICIENT_SPACE_ON_RESOURCE
                - INSUFFICIENT_STORAGE
                - INTERNAL_SERVER_ERROR
                - I_AM_A_TEAPOT
                - LENGTH_REQUIRED
                - LOCKED
                - LOOP_DETECTED
                - METHOD_FAILURE
                - METHOD_NOT_ALLOWED
                - MOVED_PERMANENTLY
                - MOVED_TEMPORARILY
                - MULTIPLE_CHOICES
                - MULTI_STATUS
                - NETWORK_AUTHENTICATION_REQUIRED
                - NON_AUTHORITATIVE_INFORMATION
                - NOT_ACCEPTABLE
                - NOT_EXTENDED
                - NOT_FOUND
                - NOT_IMPLEMENTED
                - NOT_MODIFIED
                - NO_CONTENT
                - OK
                - PARTIAL_CONTENT
                - PAYLOAD_TOO_LARGE
                - PAYMENT_REQUIRED
                - PERMANENT_REDIRECT
                - PRECONDITION_FAILED
                - PRECONDITION_REQUIRED
                - PROCESSING
                - PROXY_AUTHENTICATION_REQUIRED
                - REQUESTED_RANGE_NOT_SATISFIABLE
                - REQUEST_ENTITY_TOO_LARGE
                - REQUEST_HEADER_FIELDS_TOO_LARGE
                - REQUEST_TIMEOUT
                - REQUEST_URI_TOO_LONG
                - RESET_CONTENT
                - SEE_OTHER
                - SERVICE_UNAVAILABLE
                - SWITCHING_PROTOCOLS
                - TEMPORARY_REDIRECT
                - TOO_EARLY
                - TOO_MANY_REQUESTS
                - UNAUTHORIZED
                - UNAVAILABLE_FOR_LEGAL_REASONS
                - UNPROCESSABLE_ENTITY
                - UNSUPPORTED_MEDIA_TYPE
                - UPGRADE_REQUIRED
                - URI_TOO_LONG
                - USE_PROXY
                - VARIANT_ALSO_NEGOTIATES
                type: string
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: checkLegalTagStatusChanges
      tags:
      - legal-tag-status-job-api
  /api/legal/v1/legaltags:
    get:
      operationId: listLegalTagsUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      - description: valid
        in: query
        name: valid
        required: false
        schema:
          type: boolean
        style: form
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDtos'
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: listLegalTags
      tags:
      - legal-tag-api
    post:
      operationId: createLegalTagUsingPOST
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalTagDto'
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDto'
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: createLegalTag
      tags:
      - legal-tag-api
    put:
      operationId: updateLegalTagUsingPUT
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLegalTag'
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDto'
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: updateLegalTag
      tags:
      - legal-tag-api
  /api/legal/v1/legaltags/{name}:
    delete:
      operationId: deleteLegalTagUsingDELETE
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      - description: name
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            '*/*':
              schema:
                enum:
                - ACCEPTED
                - ALREADY_REPORTED
                - BAD_GATEWAY
                - BAD_REQUEST
                - BANDWIDTH_LIMIT_EXCEEDED
                - CHECKPOINT
                - CONFLICT
                - CONTINUE
                - CREATED
                - DESTINATION_LOCKED
                - EXPECTATION_FAILED
                - FAILED_DEPENDENCY
                - FORBIDDEN
                - FOUND
                - GATEWAY_TIMEOUT
                - GONE
                - HTTP_VERSION_NOT_SUPPORTED
                - IM_USED
                - INSUFFICIENT_SPACE_ON_RESOURCE
                - INSUFFICIENT_STORAGE
                - INTERNAL_SERVER_ERROR
                - I_AM_A_TEAPOT
                - LENGTH_REQUIRED
                - LOCKED
                - LOOP_DETECTED
                - METHOD_FAILURE
                - METHOD_NOT_ALLOWED
                - MOVED_PERMANENTLY
                - MOVED_TEMPORARILY
                - MULTIPLE_CHOICES
                - MULTI_STATUS
                - NETWORK_AUTHENTICATION_REQUIRED
                - NON_AUTHORITATIVE_INFORMATION
                - NOT_ACCEPTABLE
                - NOT_EXTENDED
                - NOT_FOUND
                - NOT_IMPLEMENTED
                - NOT_MODIFIED
                - NO_CONTENT
                - OK
                - PARTIAL_CONTENT
                - PAYLOAD_TOO_LARGE
                - PAYMENT_REQUIRED
                - PERMANENT_REDIRECT
                - PRECONDITION_FAILED
                - PRECONDITION_REQUIRED
                - PROCESSING
                - PROXY_AUTHENTICATION_REQUIRED
                - REQUESTED_RANGE_NOT_SATISFIABLE
                - REQUEST_ENTITY_TOO_LARGE
                - REQUEST_HEADER_FIELDS_TOO_LARGE
                - REQUEST_TIMEOUT
                - REQUEST_URI_TOO_LONG
                - RESET_CONTENT
                - SEE_OTHER
                - SERVICE_UNAVAILABLE
                - SWITCHING_PROTOCOLS
                - TEMPORARY_REDIRECT
                - TOO_EARLY
                - TOO_MANY_REQUESTS
                - UNAUTHORIZED
                - UNAVAILABLE_FOR_LEGAL_REASONS
                - UNPROCESSABLE_ENTITY
                - UNSUPPORTED_MEDIA_TYPE
                - UPGRADE_REQUIRED
                - URI_TOO_LONG
                - USE_PROXY
                - VARIANT_ALSO_NEGOTIATES
                type: string
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - Authorization:
        - global
      summary: deleteLegalTag
      tags:
      - legal-tag-api
    get:
      operationId: getLegalTagUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      - description: name
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseEntity'
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: getLegalTag
      tags:
      - legal-tag-api
  /api/legal/v1/legaltags:batchRetrieve:
    post:
      operationId: getLegalTagsUsingPOST
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLegalTags'
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDtos'
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: getLegalTags
      tags:
      - legal-tag-api
  /api/legal/v1/legaltags:properties:
    get:
      operationId: getLegalTagPropertiesUsingGET
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReadablePropertyValues'
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: getLegalTagProperties
      tags:
      - legal-tag-api
  /api/legal/v1/legaltags:validate:
    post:
      operationId: validateLegalTagsUsingPOST
      parameters:
      - description: tenant
        in: header
        name: data-partition-id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLegalTags'
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InvalidTagsWithReason'
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: validateLegalTags
      tags:
      - legal-tag-api
servers:
- description: Inferred Url
  url: https://uptesting0.oep.ppe.azure-int.net
tags:
- description: Health Check Api
  name: health-check-api
- description: Info Api
  name: info-api
- description: Legal Tag Api
  name: legal-tag-api
- description: Legal Tag Status Job Api
  name: legal-tag-status-job-api
