components:
  schemas:
    ConnectedOuterService:
      properties:
        name:
          type: string
        version:
          type: string
      title: ConnectedOuterService
      type: object
    IndexProgress:
      properties:
        lastUpdateTime:
          type: string
        statusCode:
          format: int32
          type: integer
        trace:
          items:
            type: string
          type: array
      title: IndexProgress
      type: object
    JaxRsDpsLog:
      title: JaxRsDpsLog
      type: object
    JobStatus:
      properties:
        debugInfos:
          items:
            type: string
          type: array
        idsByValidUpsertIndexingStatus:
          items:
            type: string
          type: array
        jaxRsDpsLog:
          $ref: '#/components/schemas/JaxRsDpsLog'
        statusesList:
          items:
            $ref: '#/components/schemas/RecordStatus'
          type: array
      title: JobStatus
      type: object
    RecordChangedMessages:
      properties:
        attributes:
          additionalProperties:
            type: string
          type: object
        data:
          type: string
        messageId:
          type: string
        publishTime:
          type: string
      title: RecordChangedMessages
      type: object
    RecordReindexRequest:
      properties:
        cursor:
          type: string
        kind:
          type: string
      required:
      - kind
      title: RecordReindexRequest
      type: object
    RecordStatus:
      properties:
        id:
          type: string
        indexProgress:
          $ref: '#/components/schemas/IndexProgress'
        kind:
          type: string
        latestTrace:
          type: string
        operationType:
          type: string
        status:
          enum:
          - FAIL
          - PROCESSING
          - SKIP
          - SUCCESS
          - WARN
          type: string
      title: RecordStatus
      type: object
    ResponseEntity:
      properties:
        body:
          type: object
        statusCode:
          enum:
          - ACCEPTED
          - ALREADY_REPORTED
          - BAD_GATEWAY
          - BAD_REQUEST
          - BANDWIDTH_LIMIT_EXCEEDED
          - CHECKPOINT
          - CONFLICT
          - CONTINUE
          - CREATED
          - DESTINATION_LOCKED
          - EXPECTATION_FAILED
          - FAILED_DEPENDENCY
          - FORBIDDEN
          - FOUND
          - GATEWAY_TIMEOUT
          - GONE
          - HTTP_VERSION_NOT_SUPPORTED
          - IM_USED
          - INSUFFICIENT_SPACE_ON_RESOURCE
          - INSUFFICIENT_STORAGE
          - INTERNAL_SERVER_ERROR
          - I_AM_A_TEAPOT
          - LENGTH_REQUIRED
          - LOCKED
          - LOOP_DETECTED
          - METHOD_FAILURE
          - METHOD_NOT_ALLOWED
          - MOVED_PERMANENTLY
          - MOVED_TEMPORARILY
          - MULTIPLE_CHOICES
          - MULTI_STATUS
          - NETWORK_AUTHENTICATION_REQUIRED
          - NON_AUTHORITATIVE_INFORMATION
          - NOT_ACCEPTABLE
          - NOT_EXTENDED
          - NOT_FOUND
          - NOT_IMPLEMENTED
          - NOT_MODIFIED
          - NO_CONTENT
          - OK
          - PARTIAL_CONTENT
          - PAYLOAD_TOO_LARGE
          - PAYMENT_REQUIRED
          - PERMANENT_REDIRECT
          - PRECONDITION_FAILED
          - PRECONDITION_REQUIRED
          - PROCESSING
          - PROXY_AUTHENTICATION_REQUIRED
          - REQUESTED_RANGE_NOT_SATISFIABLE
          - REQUEST_ENTITY_TOO_LARGE
          - REQUEST_HEADER_FIELDS_TOO_LARGE
          - REQUEST_TIMEOUT
          - REQUEST_URI_TOO_LONG
          - RESET_CONTENT
          - SEE_OTHER
          - SERVICE_UNAVAILABLE
          - SWITCHING_PROTOCOLS
          - TEMPORARY_REDIRECT
          - TOO_EARLY
          - TOO_MANY_REQUESTS
          - UNAUTHORIZED
          - UNAVAILABLE_FOR_LEGAL_REASONS
          - UNPROCESSABLE_ENTITY
          - UNSUPPORTED_MEDIA_TYPE
          - UPGRADE_REQUIRED
          - URI_TOO_LONG
          - USE_PROXY
          - VARIANT_ALSO_NEGOTIATES
          type: string
        statusCodeValue:
          format: int32
          type: integer
      title: ResponseEntity
      type: object
    SchemaChangedMessages:
      properties:
        attributes:
          additionalProperties:
            type: string
          type: object
        data:
          type: string
        messageId:
          type: string
        publishTime:
          type: string
      title: SchemaChangedMessages
      type: object
    VersionInfo:
      properties:
        artifactId:
          type: string
        branch:
          type: string
        buildTime:
          type: string
        commitId:
          type: string
        commitMessage:
          type: string
        connectedOuterServices:
          items:
            $ref: '#/components/schemas/ConnectedOuterService'
          type: array
        groupId:
          type: string
        version:
          type: string
      title: VersionInfo
      type: object
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
info:
  contact: {}
  description: Api Documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  termsOfService: urn:tos
  title: Api Documentation
  version: '1.0'
openapi: 3.0.3
paths:
  /api/indexer/v2/index:
    delete:
      operationId: deleteIndexUsingDELETE
      parameters:
      - description: data partition id
        in: header
        name: data-partition-id
        required: true
      - description: kind
        in: query
        name: kind
        required: true
        schema:
          type: string
        style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntity'
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - Authorization:
        - global
      summary: deleteIndex
      tags:
      - cleanup-indicies-api
  /api/indexer/v2/info:
    get:
      operationId: infoUsingGET
      parameters:
      - description: data partition id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: info
      tags:
      - info-api
  /api/indexer/v2/liveness_check:
    get:
      operationId: livenessCheckUsingGET
      parameters:
      - description: data partition id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: livenessCheck
      tags:
      - health-check-api
  /api/indexer/v2/partitions/provision:
    put:
      operationId: provisionPartitionUsingPUT
      parameters:
      - allowReserved: false
        description: data-partition-id
        in: header
        name: data-partition-id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: provisionPartition
      tags:
      - partition-setup-api
  /api/indexer/v2/readiness_check:
    get:
      operationId: readinessCheckUsingGET
      parameters:
      - description: data partition id
        in: header
        name: data-partition-id
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: readinessCheck
      tags:
      - health-check-api
  /api/indexer/v2/reindex:
    patch:
      operationId: fullReindexUsingPATCH
      parameters:
      - description: data partition id
        in: header
        name: data-partition-id
        required: true
      - description: force_clean
        in: query
        name: force_clean
        required: false
        schema:
          type: boolean
        style: form
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - Authorization:
        - global
      summary: fullReindex
      tags:
      - reindex-api
    post:
      operationId: reindexUsingPOST_1
      parameters:
      - description: data partition id
        in: header
        name: data-partition-id
        required: true
      - description: force_clean
        in: query
        name: force_clean
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordReindexRequest'
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - Authorization:
        - global
      summary: reindex
      tags:
      - reindex-api
servers:
- description: Inferred Url
  url: https://uptesting0.oep.ppe.azure-int.net
tags:
- description: Cleanup Indicies Api
  name: cleanup-indicies-api
- description: Health Check Api
  name: health-check-api
- description: Info Api
  name: info-api
- description: Partition Setup Api
  name: partition-setup-api
- description: Record Indexer Api
  name: record-indexer-api
- description: Reindex Api
  name: reindex-api
